[workspace]
name = "ysce-radar"
version = "0.1.0"
description = "YSCE Dual Screen Radar Mod"
authors = ["monkeydluffy"]
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = ">=3.10"
pygame = "*"
geojson = ">=3.3.0,<4"
pyqt = "5.15.11.*"
pyqtwebengine = "5.15.11.*"

[tasks]